from collections.abc import Iterator
from pathlib import Path

from mutagen import FileType
from mutagen import StreamInfo as _StreamInfo

class StreamInfo(_StreamInfo):
    sample_rate: int
    channels: int
    bits_per_sample: int

class Picture:
    type: int
    mime: str
    desc: str
    width: int
    height: int
    depth: int
    colors: int
    data: bytes
    def __init__(self, data: bytes | None = None) -> None: ...
    def write(self) -> bytes: ...

class VCFLACDict:
    def __iter__(self) -> Iterator[tuple[str, str]]: ...
    def __contains__(self, key: object) -> bool: ...
    def __getitem__(self, key: str) -> list[str]: ...
    def __setitem__(self, key: str, values: list[str] | str) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def keys(self) -> list[str]: ...
    def clear(self) -> None: ...
    def append(self, item: tuple[str, str]) -> None: ...

class FLAC(FileType):
    tags: VCFLACDict | None
    info: StreamInfo
    pictures: list[Picture]
    def __init__(self, filething: str | Path) -> None: ...
    def add_picture(self, picture: Picture) -> None: ...
    def clear_pictures(self) -> None: ...
    def save(self, filething: str | Path | None = None, deleteid3: bool = False) -> None: ...
