from collections.abc import ItemsView, Sequence, ValuesView
from pathlib import Path
from typing import Literal, overload

class Frame:
    @property
    def HashKey(self) -> str: ...

class TextFrame(Frame):
    encoding: int
    text: list[str]
    def __init__(self, *, encoding: int = 3, text: list[str] | str = ...) -> None: ...

class TCON(TextFrame):
    @property
    def genres(self) -> list[str]: ...

class TXXX(TextFrame):
    desc: str
    def __init__(self, *, encoding: int = 3, desc: str = "", text: list[str] | str = ...) -> None: ...

class COMM(TextFrame):
    desc: str
    lang: str
    def __init__(
        self, *, encoding: int = 3, lang: str = "eng", desc: str = "", text: list[str] | str = ...
    ) -> None: ...

class UFID(Frame):
    owner: str
    data: bytes
    def __init__(self, *, owner: str = "", data: bytes = b"") -> None: ...

class APIC(Frame):
    encoding: int
    mime: str
    type: int
    desc: str
    data: bytes
    def __init__(
        self, *, encoding: int = 3, mime: str = "", type: int = 3, desc: str = "", data: bytes = b""
    ) -> None: ...

Frames: dict[str, type[Frame]]

class ID3:
    version: tuple[int, int, int]
    def __init__(self, filething: str | Path | None = None) -> None: ...
    @overload
    def getall(self, key: Literal["TXXX"]) -> list[TXXX]: ...
    @overload
    def getall(self, key: Literal["COMM"]) -> list[COMM]: ...
    @overload
    def getall(self, key: Literal["APIC"]) -> list[APIC]: ...
    @overload
    def getall(self, key: Literal["TCON"]) -> list[TCON]: ...
    @overload
    def getall(self, key: str) -> Sequence[Frame]: ...
    def delall(self, key: str) -> None: ...
    def add(self, frame: Frame) -> None: ...
    def get(self, key: str) -> Frame | None: ...
    def items(self) -> ItemsView[str, Frame]: ...
    def values(self) -> ValuesView[Frame]: ...
    def clear(self) -> None: ...
    def __contains__(self, key: object) -> bool: ...
    def __delitem__(self, key: str) -> None: ...
    def save(
        self, filething: str | Path | None = None, v1: int = 1, v2_version: int = 4, v23_sep: str = "/"
    ) -> None: ...
